NAME: 'reproducing'

DATASET:
    TRAINDIR: '/home/storage/wuxian/ATR/train/image/'
    VALDIR: '/home/storage/wuxian/ATR/test/image/'
    INPUT_RES: 256
    LOCAL_RES: 128
    HOLE_MIN: 32
    HOLE_MAX: 127
    MEAN: [0.4560,  0.4472,  0.4155]

LOSS:
  ALPHA: 0.0004

TRAIN_G_EPOCHES: -1
TRAIN_D_EPOCHES: 6
  
INIT: '/home/lrl/Siggraph2018/glcic/src/completionnet_places2.t7'

SOLVER:
  WORKERS: 4
  IMG_PER_GPU: 16
  GPU_IDS: [0] # real BATCHSIZE is : IMG_PER_GPU * len(GPU_IDS) 
  LR: 0.0001
  LR_SCHEDULE: 'standard'
  OPTIMIZER: 'ADAM' # ADAM | SGD
  MOMENTUM: 0.9
  WEIGHTDECAY: 0.0004
  
LOGS:
  PRINT_FREQ: 10
  SNAPSHOT_FREQ: 500
  SNAPSHOT_MAXFILES: NOTIMPLEMENT
  SNAPSHOT_DIR: 'snapshot'
  LOG_FREQ: 100
  LOG_DIR: 'logs'
  LOG_SHUTIL_ON: true
  # shutil.copytree('./', './logs2', ignore=shutil.ignore_patterns('./logs','*.zip','*.mp4','*.jpg','*.png','__pycache__', '*.pyc'))
  LOG_SHUTIL_IGNORELIST: ['*.zip','*.mp4','*.jpg','*.png','*.pyc','*.so','*.pkl','*.caffemodel', '__pycache__','snapshot','logs']
  LOG_SHUTIL_IGNOREFILE: '.gitignore'
  
